FROM python:3.12-slim

WORKDIR /app

# Install PostgreSQL development libraries for psycopg2
RUN apt-get update && apt-get install -y libpq-dev build-essential && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY requirements-dev.txt /app/
RUN pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir -r requirements-dev.txt

COPY tasks /app

# Start Celery worker
CMD ["celery", "-A", "tasks.embed", "worker", "--loglevel=info"]

