[project]
name = "yt-assistant-emb"
version = "0.1.0"
description = "YT-Assistant embedding service"
requires-python = ">=3.11"

dependencies = [
    "celery==5.5.3",
    "langchain==0.3.25",
    "langchain-google-genai==2.1.4",
    "psycopg2==2.9.10",
    "redis==6.4.0",
]
# torch and sentence-transformers are installed with script to avoid gpu dependencies

[dependency-groups]
dev = [
    "ruff==0.14.2",
    "pytest==8.3.5",
    "pytest-asyncio==0.26.0",
    "pytest-cov==6.1.1",
    "pytest-env==1.1.5",
]
