services:

  # DATABASE
  yt_assistant_db:
    container_name: yt_assistant_db
    restart: unless-stopped
    build:
      context: ./yt_assistant_db
      dockerfile: Dockerfile.db.${ENV}
    image: yt_assistant_db:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - env/.db.env
    ports:
      - "5432:5432"
    networks:
      - app_network

  # API
  yt_assistant_api:
    container_name: yt_assistant_api
    restart: unless-stopped
    build:
      context: ./yt_assistant_api
      dockerfile: Dockerfile.api.${ENV}
    image: yt_assistant_api:latest
    volumes:
      - ./yt_assistant_api:/app
    env_file:
      - env/.api.env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - yt_assistant_db
      - yt_assistant_redis
    networks:
      - app_network

  # CLIENT
  yt_assistant_client:
    container_name: yt_assistant_client
    restart: unless-stopped
    build:
      context: ./yt_assistant_client
      dockerfile: Dockerfile.client.${ENV}
    image: yt_assistant_client:latest
    volumes:
      - ./yt_assistant_client:/app
      - /app/node_modules/
    env_file:
      - env/.client.env
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - yt_assistant_api
    networks:
      - app_network

  # REDIS
  yt_assistant_redis:
    container_name: yt_assistant_redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network
  
  # EMBEDDING WORKER
  yt_assistant_emb:
    container_name: yt_assistant_emb
    build:
      context: ./yt_assistant_emb
      dockerfile: Dockerfile.emb.${ENV}
    image: yt_assistant_emb:latest
    volumes:
      - ./yt_assistant_emb:/app
    env_file:
      - env/.emb.env
    depends_on:
      - yt_assistant_db
      - yt_assistant_redis
    networks:
      - app_network

networks:
  app_network:
    name: "${ENV}_network"
    driver: bridge

volumes:
  db_data:
    driver: local
