FROM python:3.12-slim

# Install Poetry
RUN pip install poetry==2.1.2

WORKDIR /app

# Install dependencies
COPY pyproject.toml poetry.lock* /app/
RUN poetry install --no-root

COPY . /app

EXPOSE 8000
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
