FROM python:3.12-slim

WORKDIR /app

# Install PostgreSQL development libraries for psycopg2
RUN apt-get update && apt-get install -y libpq-dev build-essential && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY requirements.txt requirements-dev.txt /app/
RUN pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt
RUN pip install torch==2.9.0+cpu --index-url https://download.pytorch.org/whl/cpu && pip install sentence-transformers==5.1.2
COPY . /app

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
