name: Setup yt_assistant_emb Environment

runs:
  using: "composite"
  steps:
    # ---------------------- Set up Python ----------------------
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # ---------------------- Install dev dependencies ----------------------
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        curl -LsSf https://astral.sh/uv/install.sh | sh
        cd yt_assistant_emb
        uv sync
        source .venv/bin/activate
        pip install --break-system-packages torch==2.9.0+cpu --index-url https://download.pytorch.org/whl/cpu
        pip install --break-system-packages sentence-transformers==5.1.2
      shell: bash
