"""add uq_conversation_account_video unique constraint for conversation

Revision ID: 700e63fedc0a
Revises: 42f3ba157f55
Create Date: 2025-10-19 18:15:57.868906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700e63fedc0a'
down_revision: Union[str, None] = '42f3ba157f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_conversation_account_video', 'conversation', ['account_id', 'video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_conversation_account_video', 'conversation', type_='unique')
    # ### end Alembic commands ###
