@startuml

entity "account" {
  *id: VARCHAR <<PK>>  // Auth0 `sub`, e.g. "auth0|abc123"
}

entity "video" {
  +id: UUID
  created_at: TIMESTAMP
  title: VARCHAR
  url: VARCHAR
}

entity "account_video" {
  +id: UUID
  created_at: TIMESTAMP
  account_id: UUID
  video_id: UUID
}

entity "transcript" {
  +id: UUID
  created_at: TIMESTAMP
  video_id: UUID
  transcript_text: TEXT
}

entity "summaries" {
  +id: UUID
  created_at: TIMESTAMP
  video_id: UUID
  summary_text: TEXT
}

entity "qa" {
  +id: UUID
  created_at: TIMESTAMP
  account_id: UUID
  video_id: UUID
  question_text: TEXT
  answer_text: TEXT
}

entity "embedding" {
  +id: UUID
  created_at: TIMESTAMP
  video_id: UUID
  embedding: vector(768)
}

'account-video relationship
account_video::account_id --> account::id
account_video::video_id --> video::id

'video-transcript relationship
transcript::video_id --> video::id

'video-summaries relationship
summaries::video_id --> video::id

'video-qa relationship
qa::video_id --> video::id
qa::account_id --> account::id

'video-embedding relationship
embedding::video_id --> video::id

@enduml