# --- Build ---
FROM node:22-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm run install
COPY . .
RUN npm run build

# --- Serve ---
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
