FROM postgres:16

# Install dependencies to build pgvector
RUN apt-get update && apt-get install -y git make gcc postgresql-server-dev-16
RUN git clone https://github.com/pgvector/pgvector.git && cd pgvector && make && make install && cd .. && rm -rf pgvector

EXPOSE 5432
