FROM postgres:16

# Install dependencies to build pgvector
RUN apt-get update && apt-get install -y git make gcc postgresql-server-dev-16
RUN git clone https://github.com/pgvector/pgvector.git && cd pgvector && make && make install && cd .. && rm -rf pgvector

# Copy init scripts for local env
COPY init_schema_local.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
