FROM postgres:16-alpine

COPY init_db.sh /docker-entrypoint-initdb.d/init_db.sh
COPY seed_dev.sql /docker-entrypoint-initdb.d/seed_dev.sql

EXPOSE 5432
RUN chmod +x /docker-entrypoint-initdb.d/init_db.sh
