name: CI

on:
  push: # any branch
  workflow_dispatch: # manual trigger
  pull_request:
    branches: [develop]

jobs:
  api-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: |
          cd yt_assistant_api
          poetry install --with dev --no-interaction
      - name: Run unit tests
        run: |
          cd yt_assistant_api
          PYTHONPATH=. poetry run pytest --cov
