name: YT-Assistant CI

on:
  push: # any branch
  workflow_dispatch: # manual trigger
  pull_request:
    branches: [develop]

jobs:
  api-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
      - name: Run api linters
        run: |
          cd yt_assistant_api
          poetry run black --check .
          poetry run isort --check .
          poetry run flake8 .

  api-unit-tests:
    runs-on: ubuntu-latest
    needs: api-lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
      - name: Run api unit tests
        run: |
          cd yt_assistant_api
          PYTHONPATH=. poetry run pytest --cov
