name: YT-Assistant CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  # ---------------------- API jobs (Poetry) ----------------------
  api-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-api-env

      - name: Run api linters
        run: |
          cd yt_assistant_api
          poetry run ruff check

  api-unit-tests:
    runs-on: ubuntu-latest
    needs: api-lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-api-env

      - name: Run api unit tests
        run: |
          cd yt_assistant_api
          PYTHONPATH=. poetry run pytest --cov

  # ---------------------- Embedding microservice jobs (pip) ----------------------
  emb-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-emb-env

      - name: Run emb linters
        run: |
          cd yt_assistant_emb
          uvx ruff check


  emb-unit-tests:
    runs-on: ubuntu-latest
    needs: emb-lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-emb-env

      - name: Run emb unit tests
        run: |
          cd yt_assistant_emb
          source .venv/bin/activate
          PYTHONPATH=. pytest --cov

